### ISSUE TITLE
Error after launching the container on the back side

### ISSUE THREAD

**Issue by RSamaium** [Sorikairox/micronation#40]
When I launch the containers with Docker:

1) `sudo docker build -t exp-flag-back .`
2) `sudo docker-compose up`

```yml
version: '3.7'

services:
  mongo:
    image: mongo

  dirtybiology-back:
    image: exp-flag-back
    ports:
      - 3000:3000
    environment:
        DATABASE_URI: "mongodb://mongo:27017/test"
        DIRECTUS_URL: https://dev.fouloscopie.com
        PORT: 3000
```

Error:

```
dirtybiology-back_1  | Error: Cannot find module 'library/database/repository/DatabaseRepository'
dirtybiology-back_1  | Require stack:
dirtybiology-back_1  | - /usr/src/app/flag-service/dist/flag/pixel/PixelRepository.js
dirtybiology-back_1  | - /usr/src/app/flag-service/dist/flag/FlagService.js
dirtybiology-back_1  | - /usr/src/app/flag-service/dist/flag/FlagController.js
dirtybiology-back_1  | - /usr/src/app/flag-service/dist/flag/FlagModule.js
dirtybiology-back_1  | - /usr/src/app/flag-service/dist/bootstrap.js
dirtybiology-back_1  | - /usr/src/app/flag-service/dist/main.js
dirtybiology-back_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
dirtybiology-back_1  |     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
dirtybiology-back_1  |     at Module.require (internal/modules/cjs/loader.js:974:19)
dirtybiology-back_1  |     at require (internal/modules/cjs/helpers.js:93:18)
dirtybiology-back_1  |     at Object.<anonymous> (/usr/src/app/flag-service/dist/flag/pixel/PixelRepository.js:16:30)
dirtybiology-back_1  |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
dirtybiology-back_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
dirtybiology-back_1  |     at Module.load (internal/modules/cjs/loader.js:950:32)
dirtybiology-back_1  |     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
dirtybiology-back_1  |     at Module.require (internal/modules/cjs/loader.js:974:19) {
dirtybiology-back_1  |   code: 'MODULE_NOT_FOUND',
dirtybiology-back_1  |   requireStack: [
dirtybiology-back_1  |     '/usr/src/app/flag-service/dist/flag/pixel/PixelRepository.js',
dirtybiology-back_1  |     '/usr/src/app/flag-service/dist/flag/FlagService.js',
dirtybiology-back_1  |     '/usr/src/app/flag-service/dist/flag/FlagController.js',
dirtybiology-back_1  |     '/usr/src/app/flag-service/dist/flag/FlagModule.js',
dirtybiology-back_1  |     '/usr/src/app/flag-service/dist/bootstrap.js',
dirtybiology-back_1  |     '/usr/src/app/flag-service/dist/main.js'
dirtybiology-back_1  |   ]
dirtybiology-back_1  | }
```
